### ISSUE TITLE
error with Lokhttp3/HttpUrl;

### ISSUE THREAD

**Issue by VincentDugard** [Kpler/auth0-guardian-flutter#2]
Hello,

Thanks for your library  🙏
I try to run your example project using android device.
I can scan the Auth0 QR code but when I click "Step 2" I get this error

```
E/AndroidRuntime( 7299): FATAL EXCEPTION: main
E/AndroidRuntime( 7299): Process: com.kpler.auth0_guardian_example, PID: 7299
E/AndroidRuntime( 7299): java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/HttpUrl;
E/AndroidRuntime( 7299):        at com.auth0.android.guardian.sdk.GuardianAPIClient$Builder.url(GuardianAPIClient.java:332)
E/AndroidRuntime( 7299):        at com.auth0.android.guardian.sdk.Guardian$Builder.build(Guardian.java:276)
E/AndroidRuntime( 7299):        at com.kpler.auth0_guardian_flutter.GuardianFlutter.buildGuardian(GuardianFlutter.kt:43)
E/AndroidRuntime( 7299):        at com.kpler.auth0_guardian_flutter.GuardianFlutter.enroll(GuardianFlutter.kt:75)
E/AndroidRuntime( 7299):        at com.kpler.auth0_guardian_flutter.GuardianFlutter.onMethodCall(GuardianFlutter.kt:33)
E/AndroidRuntime( 7299):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime( 7299):        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime( 7299):        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime( 7299):        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 7299):        at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 7299):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7299):        at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime( 7299):        at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime( 7299):        at android.app.ActivityThread.main(ActivityThread.java:9063)
E/AndroidRuntime( 7299):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7299):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
E/AndroidRuntime( 7299):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by Bazni** [comment]
Hey 👋,
Which version of Android and Java do you use?
